### ISSUE TITLE
Does not support version 1.21.2-1.21.3

### ISSUE THREAD

**Issue by VictorSkr** [MachiganMC/ProtectedDebugStick#24]
When trying to run the plugin on these versions it gives two errors in the server console, causing it to refuse to work:

```
[22:26:09 ERROR]: [ProtectedDebugStick] The plugin doesn't support you're server version
[22:26:09 ERROR]: [ProtectedDebugStick] No valid properties has been found for you're server version
```

**Comment by MachiganMC** [comment]
Hello, yes I have to add the support for the new versions.
I'll add it in the next version, soon

**Comment by NoltoxGit** [comment]
Hi @MachiganMC,
Do you have any news about the support of newer versions in official releases?

**Comment by MachiganMC** [comment]
Hello, I added the support to Mincraft 1.23 and 1.21.4 (1.21.2 for Spigot doesn't exist, it's just 1.21.3)
Big thanks to @BAD7777 for the help in #26 , I have a little modified the code 😄 
I didn't added the property concerning the creaking heart because Spigot has tagged it as unstable. I'll add it when it will be stable.

I will now write the update
